# LAB 2- Data Preprocessing Tools

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing Dataset

In [2]:
dataset = pd.read_csv("C:\\Users\\gauri\\Downloads\\flights.csv")

## EDA Steps

In [3]:
dataset.head()

Turbulence_Level  Wind_Speed_Knot  Visibility_km  Status
0             High             45.0           19.0      ok
1              Low              NaN            6.0  not ok
2           Medium             48.0            6.0      ok
3             High             48.0           18.0  not ok
4              Low             34.0           20.0      ok

In [4]:
dataset.shape

(15, 4)

In [5]:
dataset.columns

Index(['Turbulence_Level', 'Wind_Speed_Knot', 'Visibility_km', 'Status'], dtype='object')

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Turbulence_Level  15 non-null     object 
 1   Wind_Speed_Knot   13 non-null     float64
 2   Visibility_km     14 non-null     float64
 3   Status            15 non-null     object 
dtypes: float64(2), object(2)
memory usage: 612.0+ bytes


In [7]:
dataset.describe

<bound method NDFrame.describe of    Turbulence_Level  Wind_Speed_Knot  Visibility_km  Status
0              High             45.0           19.0      ok
1               Low              NaN            6.0  not ok
2            Medium             48.0            6.0      ok
3              High             48.0           18.0  not ok
4               Low             34.0           20.0      ok
5            Medium             46.0           15.0      ok
6              High             47.0           12.0      ok
7               Low             10.0            4.0  not ok
8            Medium             29.0           20.0      ok
9              High              2.0            7.0      ok
10           Medium             15.0           14.0      ok
11             High             36.0           11.0      ok
12           Medium              NaN            6.0  not ok
13           Medium             26.0            NaN  not ok
14              Low             40.0           13.0      ok>

In [8]:
# descriptive statastics for categorical features
dataset.describe(include= 'object')

Turbulence_Level Status
count                15     15
unique                3      2
top              Medium     ok
freq                  6     10

## Preprocessing Steps

### Step 1: Divide Dataframe into independant variable/ input and dependant/ output features

In [9]:
X = dataset.iloc [ : , :-1 ]
Y = dataset.iloc [ : , -1]

In [11]:
print(X)

   Turbulence_Level  Wind_Speed_Knot  Visibility_km
0              High             45.0           19.0
1               Low              NaN            6.0
2            Medium             48.0            6.0
3              High             48.0           18.0
4               Low             34.0           20.0
5            Medium             46.0           15.0
6              High             47.0           12.0
7               Low             10.0            4.0
8            Medium             29.0           20.0
9              High              2.0            7.0
10           Medium             15.0           14.0
11             High             36.0           11.0
12           Medium              NaN            6.0
13           Medium             26.0            NaN
14              Low             40.0           13.0


In [10]:
print(Y)

0         ok
1     not ok
2         ok
3     not ok
4         ok
5         ok
6         ok
7     not ok
8         ok
9         ok
10        ok
11        ok
12    not ok
13    not ok
14        ok
Name: Status, dtype: object


### Step 2: Handle the mising values in dataset

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
imputer = SimpleImputer(missing_values = np.nan,
                       strategy = 'mean')
imputer.fit(X.iloc[:,1:3])
X.iloc[:,1:3] = imputer.transform(X.iloc[:,1:3])

In [13]:
print(X)

   Turbulence_Level  Wind_Speed_Knot  Visibility_km
0              High        45.000000      19.000000
1               Low        32.769231       6.000000
2            Medium        48.000000       6.000000
3              High        48.000000      18.000000
4               Low        34.000000      20.000000
5            Medium        46.000000      15.000000
6              High        47.000000      12.000000
7               Low        10.000000       4.000000
8            Medium        29.000000      20.000000
9              High         2.000000       7.000000
10           Medium        15.000000      14.000000
11             High        36.000000      11.000000
12           Medium        32.769231       6.000000
13           Medium        26.000000      12.214286
14              Low        40.000000      13.000000


### Step 3: Encoding Categorical Data

In [14]:
dataset['Turbulence_Level'].value_counts()

Turbulence_Level
Medium    6
High      5
Low       4
Name: count, dtype: int64

In [15]:
dataset['Status'].value_counts()

Status
ok        10
not ok     5
Name: count, dtype: int64

#### A Encoding the independant variable(i/p Feature/X)
#### It has 3 categories So used onehot encoder

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder',
                                     OneHotEncoder(),
                                     [0])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
print(X)

[[ 1.          0.          0.         45.         19.        ]
 [ 0.          1.          0.         32.76923077  6.        ]
 [ 0.          0.          1.         48.          6.        ]
 [ 1.          0.          0.         48.         18.        ]
 [ 0.          1.          0.         34.         20.        ]
 [ 0.          0.          1.         46.         15.        ]
 [ 1.          0.          0.         47.         12.        ]
 [ 0.          1.          0.         10.          4.        ]
 [ 0.          0.          1.         29.         20.        ]
 [ 1.          0.          0.          2.          7.        ]
 [ 0.          0.          1.         15.         14.        ]
 [ 1.          0.          0.         36.         11.        ]
 [ 0.          0.          1.         32.76923077  6.        ]
 [ 0.          0.          1.         26.         12.21428571]
 [ 0.          1.          0.         40.         13.        ]]


#### B. Encoding the dependant variable(o/p feature/ target / Y)
#### Here it has 2 categories i.e ok, not ok So used Label encoder

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

Y = le.fit_transform(Y)

In [19]:
print(Y)

[1 0 1 0 1 1 1 0 1 1 1 1 0 0 1]


### Step 4: Splitting data into Training and testing

In [20]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                        test_size = 0.3,
                                    random_state =1)

In [21]:
print(X_train)

[[ 0.          1.          0.         34.         20.        ]
 [ 0.          1.          0.         32.76923077  6.        ]
 [ 0.          0.          1.         26.         12.21428571]
 [ 1.          0.          0.         45.         19.        ]
 [ 0.          1.          0.         40.         13.        ]
 [ 1.          0.          0.          2.          7.        ]
 [ 0.          0.          1.         29.         20.        ]
 [ 0.          0.          1.         32.76923077  6.        ]
 [ 1.          0.          0.         36.         11.        ]
 [ 0.          0.          1.         46.         15.        ]]


In [22]:
print(X_test)

[[ 1.  0.  0. 48. 18.]
 [ 0.  1.  0. 10.  4.]
 [ 1.  0.  0. 47. 12.]
 [ 0.  0.  1. 48.  6.]
 [ 0.  0.  1. 15. 14.]]


### Step 5: Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])

In [26]:
print(X_test)

[[ 1.          0.          0.          0.83216143  1.39707095]
 [ 0.          1.          0.         -1.36382013 -1.31945589]
 [ 1.          0.          0.          0.77437245  0.23284516]
 [ 0.          0.          1.          0.83216143 -0.93138063]
 [ 0.          0.          1.         -1.07487519  0.62092042]]


### Q.1 When to use the label encoder and When to use the one hot encoder ?

In [ ]:
Label encoding and one-hot encoding are both techniques used to convert
categorical data into a format that can be provided to ML algorithms.  

Label Encoding:
Use when the categorical feature is ordinal (i.e., there is a meaningful order) or when the number of unique categories 
is high. Label encoding assigns a unique integer to each category, effectively converting categorical variables into 
numerical ones. Suitable for algorithms that can interpret ordinal relationships, like decision trees or random forests.
However, label encoding may introduce unintended ordinal relationships where none exist. 
For example, if you encode categories as 0, 1, 2, etc., some algorithms may interpret the numerical 
difference between categories as meaningful.

One-Hot Encoding:
Use when the categorical feature is nominal (i.e., there is no meaningful order) or when the number of unique categories 
is manageable. One-hot encoding creates a binary column for each category and returns a sparse matrix where each row has 
a single 1 indicating the presence of that category. 

### Q.2 Write a code to Feature Scaling our dataset numerical variable using MinMaxScaler

In [29]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
mmc=MinMaxScaler()
X_train[:,3:] = mmc.fit_transform(X_train[:,3:])
X_test[:,3:] = mmc.fit_transform(X_test[:,3:])

In [30]:
print(X_test)

[[1.         0.         0.         1.         1.        ]
 [0.         1.         0.         0.         0.        ]
 [1.         0.         0.         0.97368421 0.57142857]
 [0.         0.         1.         1.         0.14285714]
 [0.         0.         1.         0.13157895 0.71428571]]


### Q.3. For the below student dataset remove missing values from column ‘gender’ and ‘marks’
###### import pandas as pd
###### import numpy as np
###### students = [[85, 'M', 'verygood'],
###### [95, 'F', 'excellent'],
###### [75, None,'good'],
###### [np.NaN, 'M', 'average'],
###### [70, 'M', 'good'],
###### [np.NaN, None, 'verygood'],
###### [92, 'F', 'verygood'],
###### [98, 'M', 'excellent']]
###### dfstd = pd.DataFrame(students)
###### dfstd.columns = ['marks', 'gender', 'result']

In [31]:
import pandas as pd
import numpy as np

students = [
    [85, 'M', 'verygood'],
    [95, 'F', 'excellent'],
    [75, None, 'good'],
    [np.NaN, 'M', 'average'],
    [70, 'M', 'good'],
    [np.NaN, None, 'verygood'],
    [92, 'F', 'verygood'],
    [98, 'M', 'excellent']
]

dfstd = pd.DataFrame(students)
dfstd.columns = ['marks', 'gender', 'result']

# Remove missing values from 'gender' and 'marks' columns
dfstd_cleaned = dfstd.dropna(subset=['gender', 'marks'])

print(dfstd_cleaned)


   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
4   70.0      M       good
6   92.0      F   verygood
7   98.0      M  excellent


In [32]:
import pandas as pd
import numpy as np

students = [
    [85, 'M', 'verygood'],
    [95, 'F', 'excellent'],
    [75, None, 'good'],
    [np.NaN, 'M', 'average'],
    [70, 'M', 'good'],
    [np.NaN, None, 'verygood'],
    [92, 'F', 'verygood'],
    [98, 'M', 'excellent']
]

dfstd = pd.DataFrame(students)
dfstd.columns = ['marks', 'gender', 'result']

# Convert 'gender' and 'result' columns to category type
dfstd['gender'] = dfstd['gender'].astype('category')
dfstd['result'] = dfstd['result'].astype('category')

# Display the encoded DataFrame
print(dfstd)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   75.0    NaN       good
3    NaN      M    average
4   70.0      M       good
5    NaN    NaN   verygood
6   92.0      F   verygood
7   98.0      M  excellent
