# Support Vector Machine (SVM)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
%pylab inline
pylab.rcParams['figure.figsize'] = (10, 6)


%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


## Importing the dataset

In [2]:
wine = datasets.load_wine()
print(wine)
X = wine.data[:, :]
y = wine.target


{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

## Exploratory Data Analysis
###  Place the iris data into a pandas dataframe

In [3]:
wine_df = pd.DataFrame(wine.data[:,:], columns=wine.feature_names[:])

# View the first 5 rows of the data
print(wine_df.head())

# Print the unique labels of the dataset
print('\n' + 'The unique labels in this data are ' + str(np.unique(y)))


   alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                  

In [4]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=0)

print('There are {} samples in the training set and {} samples in the test set'.format(
X_train.shape[0], X_test.shape[0]))


There are 133 samples in the training set and 45 samples in the test set


## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(X_train)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

print('After standardizing our features, the first 5 rows of our data now look like this:\n')
print(pd.DataFrame(X_train_std, columns=wine_df.columns).head())


After standardizing our features, the first 5 rows of our data now look like this:

    alcohol  malic_acid       ash  alcalinity_of_ash  magnesium  \
0  0.799969    0.634004  0.717833          -1.227784   1.076995   
1 -0.498760    0.061720 -0.610727          -0.288160  -0.447576   
2 -1.297977   -1.163326 -0.241683           0.423677   0.037515   
3 -0.935832    1.331475 -0.610727          -0.288160   0.799801   
4  1.624162   -0.421145  1.308304           0.138942   1.354190   

   total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
0       0.717575    1.093799             -1.522752         0.084380   
1      -1.050089   -1.321955              2.088177        -1.118040   
2       1.830549    0.186617             -1.836746         0.067680   
3      -1.442903   -1.199639             -0.580770        -0.784034   
4       0.881248    1.205923             -0.266777         0.602089   

   color_intensity       hue  od280/od315_of_diluted_wines   proline  
0        -0.005

## Training the SVM model on the Training set

In [7]:
from sklearn.svm import SVC

svm = SVC(kernel='rbf', random_state=0, gamma='auto', C=1.0)
svm.fit(X_train_std, y_train)


SVC(gamma='auto', random_state=0)

### Dispplay the support Vectors of model

In [8]:
print("Support Vector for model are :",svm.support_vectors_)

Support Vector for model are : [[ 3.75384367e-01 -5.99983912e-01 -8.32153710e-01 -7.15261889e-01
  -4.47575682e-01  2.26557322e-01  2.37582551e-01 -7.37767359e-01
  -4.33328276e-01 -4.85395973e-01  3.12505585e-01  2.54666687e-01
   1.77109171e+00]
 [ 3.00457722e-01  1.42089422e+00 -2.78586970e-01 -5.72894587e-01
   1.76112434e-01  6.19371537e-01  6.86077097e-01 -3.45275124e-01
   8.43803539e-02 -3.14288322e-01 -5.47660864e-01  5.73026063e-01
  -2.31028190e-01]
 [ 6.31900147e-02 -5.91041973e-01 -1.20119820e+00 -2.02504107e+00
  -5.86173041e-01  7.50309609e-01  1.33843280e+00 -1.52275183e+00
   2.17191515e+00  8.70945165e-01  7.42588810e-01  4.48450655e-01
   1.32433768e+00]
 [ 2.18611161e+00 -5.91041973e-01  9.04575223e-02 -2.30977567e+00
  -6.55471720e-01  1.37226545e+00  1.76654123e+00  5.18207793e-01
   2.00491237e+00  1.19740843e-01  1.30169700e+00  1.99299839e-01
   1.32433768e+00]
 [-1.86565467e-01 -7.07287176e-01  5.70215363e-01 -4.87474206e-01
  -3.78277002e-01  3.57495393e-01  

In [9]:
print("Number of suppoort Vectors of each class 0 : - ",svm.n_support_[0])
print("Number of suppoort Vectors of each class 1 : - ",svm.n_support_[1])
print("Number of suppoort Vectors of each class 2 : - ",svm.n_support_[2])

Number of suppoort Vectors of each class 0 : -  16
Number of suppoort Vectors of each class 1 : -  27
Number of suppoort Vectors of each class 2 : -  17


In [10]:
print("Indices for support vectors are : ",svm.support_)

Indices for support vectors are :  [ 16  27  38  48  50  52  58  69  77  79  90 102 115 119 125 126   2  13
  17  20  22  24  25  26  29  30  33  42  43  44  54  56  60  62  76  81
 100 109 110 113 114 116 123   3   6   8  12  18  37  65  67  68  72  84
  88  91  93 101 118 121]


## Finding Accuracy of model on Test and Train Set

In [11]:
print('The accuracy of the svm classifier on training data is {:.2f} out of 1'.format(svm.score(X_train_std, y_train)))

print('The accuracy of the svm classifier on test data is {:.2f} out of 1'.format(svm.score(X_test_std, y_test)))

The accuracy of the svm classifier on training data is 0.99 out of 1
The accuracy of the svm classifier on test data is 1.00 out of 1


## Finding Accuracy of model on using confiusion matrix

In [12]:
from sklearn.metrics import confusion_matrix

confusion_matrix = confusion_matrix(y_test, svm.predict(X_test_std))
print(confusion_matrix)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]


In [13]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

Accuracy = accuracy_score(y_test, svm.predict(X_test_std))
Precision = precision_score(y_test, svm.predict(X_test_std),average='macro')
Sensitivity_recall = recall_score(y_test, svm.predict(X_test_std),average='macro')
Specificity = recall_score(y_test, svm.predict(X_test_std), pos_label=0,average='macro')
F1_score = f1_score(y_test, svm.predict(X_test_std),average='macro')

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1521: UserWarning: Note that pos_label (set to 0) is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [14]:
#metrics
print({"Accuracy":Accuracy,
       "Precision":Precision,
       "Sensitivity_recall":Sensitivity_recall,
       "Specificity":Specificity,
       "F1_score":F1_score},end = "")

{'Accuracy': 1.0, 'Precision': 1.0, 'Sensitivity_recall': 1.0, 'Specificity': 1.0, 'F1_score': 1.0}

## Tasks

#### 1) For the model we created in the lab session write the following results

In [15]:
print("Number of suppoort Vectors of each class 0 : - ",svm.n_support_[0])
print("Number of suppoort Vectors of each class 1 : - ",svm.n_support_[1])
print("Number of suppoort Vectors of each class 2 : - ",svm.n_support_[2])

Number of suppoort Vectors of each class 0 : -  16
Number of suppoort Vectors of each class 1 : -  27
Number of suppoort Vectors of each class 2 : -  17


#### Accuracy of Model= 1.0

In [16]:
# Training Accuracy
print("Training Accuracy=",svm.score(X_train, y_train))
# Testing Accuracy
print("Testing Accuracy=",svm.score(X_test, y_test))

Training Accuracy= 0.37593984962406013
Testing Accuracy= 0.4666666666666667


#### Precision = 1.0
#### F1 Score = 1.0

#### Crete the model with following settings
kernel='poly', 
degree = Other than 3 any integer number preferably 5
random_state= any number of your choice, 
coef0 = any float number of your choice other than 0.0
gamma=.10, 
C=1.0

In [17]:
from sklearn.svm import SVC
# Define the SVM model with polynomial kernel
svm = SVC(kernel='poly', degree=5, random_state=6, coef0=1.5, 
 gamma=0.1, C=1.0)
# Assuming X_train_std and y_train are your training data
svm.fit(X_train_std, y_train)

SVC(coef0=1.5, degree=5, gamma=0.1, kernel='poly', random_state=6)

In [18]:
print("Number of support vectors of class 0:", svm.n_support_[0])
print("Number of support vectors of class 1:", svm.n_support_[1])

Number of support vectors of class 0: 10
Number of support vectors of class 1: 16


In [19]:
# 1. Training Accuracy
print("Training accuracy =", svm.score(X_train_std, y_train))
# 2. Testing Accuracy
print("Testing accuracy =", svm.score(X_test_std, y_test))

Training accuracy = 1.0
Testing accuracy = 0.9777777777777777


In [20]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
Accuracy = accuracy_score(y_test, svm.predict(X_test_std))
print("Accuracy: ", Accuracy)
Precision = precision_score(y_test, svm.predict(X_test_std),average='macro')
print("Precision: ", Precision)
F1_score = f1_score(y_test, svm.predict(X_test_std),average='macro')
print("F1_score: ", F1_score)

Accuracy:  0.9777777777777777
Precision:  0.9803921568627452
F1_score:  0.9817689085981769
